version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: improvbyexample_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --notify-keyspace-events Ex
  
volumes:
  postgres_dev_data:
  pgadmin_data:
