version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: improvbyexample-postgres
    environment:
      POSTGRES_DB: improvbyexample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - improvbyexample-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: improvbyexample-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - improvbyexample-network
    command: redis-server --appendonly yes

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: improvbyexample-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=improvbyexample;Username=postgres;Password=password
      - ConnectionStrings__Redis=redis:6379
    networks:
      - improvbyexample-network
    volumes:
      - ../src:/app/src
    profiles:
      - full-stack

volumes:
  postgres_data:
  redis_data:

networks:
  improvbyexample-network:
    driver: bridge